export const COMPLIMENTS = [
    'Anlatsana biraz neden bu kadar mükemmelsin?',
    'birbirimizi çift görmem için kaç duble daha içmeliyim?',
    'beni biraz takar mısın?',
    'Çikolatalı keksin bu alemde teksin',
    'Kakaolu sütsün seni sevmeyen ölsün',
    'meleksin ama canımı alıyorsun yoksa Azrailim misin?',
    'Hangi davalara bakıyorsun söyle de o suçu işliyim',
    'Oha bu çocuk Türk müüüüüüüüüüüü?',
    'Ben küçücük bi botum ama sana kocaman sarılırım',
    'Bana yüzünü dönme gece oluyor sanıyorum.',
    'bu güne aynayı öperek başladım',
    'Sana gemi alalım dümende bir numarasın.',
    'Numaramı soran olursa, değiştirmedim hala 1 numarayım',
    'yemeğimi yedim şimdi seni yeme vakti',
    'Corona olsan bile sana sarılırdım',
    'Kafam çok güzel çünkü içinde sen varsın.',
    'akıllara zarar bi mükemmelliğin var',
    'Hayatımın özeti; bu sayfa görüntülenemiyor.',
    'Buralarda yeniyim de kalbinin yolunu tarif eder misin?',
    'Sokakları bilmem ama benim gönlüm hep sana çıkıyor',
    'seni her gün görenlerin şansından istiyorum',
    'en iyisine layıksın yani bana hıh',
    'bunun adı kalp güzelim. Tersten okuduğun gibi plak değil ki sürekli sende takılı kalsın.',
    'Yarın sokağa çıkma yasağı olmasa ne olur benim sokağım sana çıkmadıktan sonra',
    'Dün hastaneye gittim kalp röntgenimi çektiler. çok güzel çıkmışsın',
    'Dünyanın en güzel manzarasına sırtımı döner gülüşünü izlerim',
    'çok güzel bi tablo gördüm tam alacaktım ama aynaymış...',
    'canın yandı mı? cenneten düşerken?',
    'Nasılsın diye sorma bebeğim, sana göreyim kıpss',
    'taş gibisin!',
    'Polisi arıyorum çünkü bu kadar tatlı olman yasadışı !',
    'bi alo de gelmezsem gençliğim solsun.',
    'Güneş aya ben sana tutuldum.',
    'Oha sen gerçek misin ?',
    'Gece oluncа bir sessizlik, sensizlik.',
    'Canımın içi, sen hangi şiirden kaçıp geldin yüreğimin orta yerine?',
    'sarılalım mı?',
    'sen beni bir de sevgilinken gör',
    'hava sıcak değil aşkından yanıyorum',
    'dalin gibi kokuyorsun',
    'benimle evlenir misin?',
    'Kalbinin yolunu gösterir misin...',
    'Çünkü sen komutuma debug oldun',
    'Verilmiş sadakam varsa geri alabilir miyim? Paraya sıkıştım da.',
    'azrail bile ayağıma geliyor ne bu tripler?',
    'Şey gözlerin çok güzelmiş tanışalım mı ?',
    'sütüm yarım yağlı mutluluğum sana bağlı',
    'sana hayatım diyorum çünkü o kadar kötüsün',
    'Telefon numaramı kaybettimde, seninkini alabilir miyim?',
    'Sana hayatım diyemem, bu kadar güzel bir yaşantım olmadı…',
    'seni seviyorum.',
    'Her şeyimi öğrenmek istiyorsan aynaya bakabilirsin',
    'Ölmene gerek yok, yanıma gel mekanın cennet olsun',
    'öpşuelimi? çabuk!',
    'Hukuk okusam nolur seni görünce aklıma hakim olamadıktan sonra',
    'iban at hayallerimi yollayayım harcarsın',
    'Kaşların yay kirpiğin ok gibi vurduğunu öldürürsün, geçme mescid kapısından çok namazlar böldürürsün...',
    'yavrum hepsi senin mi?',
    'eğer ahtapot olsaydım üç kalbimi de sana verirdim',
    'Nasıl yani şimdi sen gerçek misin?',
    'Suyun içinde klorür senin kalbinde bir ömür...',
    '2 bedende tek ruh değil miyiz sence de?',
    'Bunca zaman neredeydin ?',
    'sevgilim var yazma?',
    'Teknoloji çok ilerledi, güneşi bu kadar yakından görebildiğimize göre',
    'Alnın güzelmiş yazısı olabilir miyim ?',
    'iyi ki varsın 💕',
    'senin hava attığın yerde benim rüzgarım esiyor',
    'zenginsen evlenelim mi?',
    'attan indiysek leopar falan gelmiştir ben anlamam eşekten',
    'ateşimin çıkma sebebi corona değil, sensin',
    'Ölüm ani dünya fani bi kere sevsen nolur ki yani ?',
    'Ya sen hep böyle hoşuma mı gideceksin ?',
    'canım haddin hariç her şeyi biliyorsun',
    'Ne Sinovac vuruldum ne Biontech ben sana vuruldum bir tek...',
    'ben varya fay hattı olsam kesin daha az kırılırdım',
    'tavla oynayalım ama sen beni tavla',
    'üşüdüysen sana abayı yakayım mı?',
    '10 parmağında 10 marifet olmasına gerek yok, bir parmağında yüzüğüm olsun yeter',
    'aklın başına gelir ama ben sana gelmem',
    'o kadar haklısın ki... seni öpesim var',
    'Dünya kütüphanesindeki en güzel kitapsın',
    'sqrt(cos(x))cos(300x)+sqrt(abs(x))-0.7)(4-x*x)^0.01 sqrt(6-x^2)from-4.5 to 4.5',
    'AÇILIN DÜNYANIN 8.HARİKASI GELDİ !',
    'Çok tatlı olmayı bırak artık... Kalbim başa çıkamıyor !',
    'Seni bir sonraki nefesimi bekler gibi bekliyorum',
    'seni mumla ararken elektrikler geldi',
    'Kalbini dinle dediklerinde seni dinleyesim geliyor',
    'Ampulü Edison icat etti ama ışığı sen saçıyorsun',
    '8 milyar gülüş varken seninki favorim',
    'konum atta belamızı bulalım bebeğim',
    'Gülüşün şimşek içermiyiz birer milkşeyk ?',
    'Üzerinde pijama olsa bile, nasıl oluyor da her zaman bu kadar güzel görünüyorsun?',
    'artık benimsin',
];
